### ISSUE TITLE
Javascript errors abound while navigating Admin and Blog areas

### ISSUE THREAD

**Issue by ajtatum** [ofpinewood/pineblog#100]
To me, something seems to be off with the RazorPages package as it looks like it should handle all of this. However, I almost began resolving it by taking the code from the RazorPages project and manually implementing the JS/CSS it was looking for, but still received this error when I'd navigate to the new posts page:

```
jquery.js:3818 jQuery.Deferred exception: SimpleMDE is not defined ReferenceError: SimpleMDE is not defined
    at HTMLDocument.<anonymous> (https://localhost:5456/admin/addpost:430:29)
    at mightThrow (https://localhost:5456/lib/jquery/dist/jquery.js:3534:29)
    at process (https://localhost:5456/lib/jquery/dist/jquery.js:3602:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3818
process @ jquery.js:3606
setTimeout (async)
(anonymous) @ jquery.js:3640
fire @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
fire @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
completed @ jquery.js:3888
jquery.js:3827 Uncaught ReferenceError: SimpleMDE is not defined
    at HTMLDocument.<anonymous> (addpost:430)
    at mightThrow (jquery.js:3534)
    at process (jquery.js:3602)
```

I have jQuery and popper installed (in the footer) and they're the same versions you're using. 

If I go to the /blog page, I get the following:

```
GET https://localhost:5456/themes/default/css/theme.css net::ERR_ABORTED 404
GET https://localhost:5456/themes/default/js/theme.min.js net::ERR_ABORTED 404
```

So, something seems off. 

I have the following packages installed:
Opw.PineBlog
Opw.PineBlog.Core
Opw.PineBlog.EntityFrameworkCore
Opw.PineBlog.RazorPages

In my startup.cs file, I have:

```
services.AddPineBlog(Configuration);

 services.AddRazorPages()
                .AddPineBlogRazorPages()
                .AddRazorPagesOptions(o =>
                {
                    o.Conventions.AuthorizeFolder("/mysticalfolder");
                })
                .AddNewtonsoftJson(x => x.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore)
                .AddRazorRuntimeCompilation();
```
I've tried moving AddPineBlogRazorPages to various parts of the AddRazorPages method, but didn't notice any change.

Sorry to bombard you with questions suddenly; however, I appreciate you taking a look. Perhaps it's something simple and I've configured it wrong, or perhaps I misunderstand the concepts and am supposed to build out all the template files like in the Razor project. 

Let me know...

Thank you,
AJ

**Comment by petervandenhout** [comment]
@ajtatum I've tried to reproduce the issues you are having, but I don't get those. Could you have a look at this PR #102 and see if you get them when you run the `Opw.PineBlog.Sample.NuGet` project?

**Comment by petervandenhout** [comment]
@ajtatum I can only reproduce the issues when I disable static file serving. 
Can you make sure you enable static file serving `app.UseStaticFiles();`, to enable the serving of the css and javascript from the `Opw.PineBlog.RazorPages` packages.

**Comment by ajtatum** [comment]
Your sample project works great. I eventually got things to work _somewhat_ on my end by manually including the simplemde.js, dataservice.js, and filemanager.js files after calling @RenderSection("scripts", required: false). Even then, the editor wasn't displaying some of the icons. Looking at the dev tools, it appears it could be because it's trying to load fontawesome 4.7.0 whereas in my layout header I'm using fontawesome pro 5.14. So, it could possible be because of versioning conflicts. I was also using an older version of bootstrap. As to why the scripts won't render automatically, I have no idea... I do have app.UseStaticFiles(). I wish I had better or more helpful news. I may end up forking this project to remove some of the dependencies or build something just for my use case, which would be unfortunate because this looked perfect. I **truly** appreciate your quick response. If you'd like me to test things out in the future, please let me know.

Thanks,
AJ


![2020-09-04 15_41_36-Window](https://user-images.githubusercontent.com/318022/92279635-b6bc8e80-eec5-11ea-90c0-c3ca97e757d0.png)

**Comment by petervandenhout** [comment]
@ajtatum that is too bad, I really hoped we could get it working for you. But without having a way to reproduce the issues you have I can't do mush more..
Could you fork the project and update the sample project so that it also has those issues, that way I could maybe solve them. But that might be some work to update to sample project to have the same issue, I don't know if you have the time for that..

**Comment by petervandenhout** [comment]
@ajtatum I'm closing the issue, if you have any other issues let me know.
