### ISSUE TITLE
Failures out of box on setup

### ISSUE THREAD

**Issue by benmac** [ofpinewood/pineblog#104]
Hi, i have created a fresh new project in VS2019 - ASP.net core web app - MVC and have followed the instructions for getting started.
1. Added package Opw.PineBlog v 1.3.4
2. ConfigureServices() added  services.AddPineBlogCore(Configuration);/services.AddRazorPages().AddPineBlogRazorPages();
3.Configure() added  endpoints.MapRazorPages();/endpoints.MapControllers();
4. CreateHostBuilder() added config.AddPineBlogEntityFrameworkCoreConfiguration(reloadOnChange: true);
Note: documentation is inconsistent for this step - some says AddPineBlogEntityFrameworkCoreConfiguration other says AddPineBlogConfiguration (Which doesnt resolve)
5. i have done nothing else to the project
on compile and running i am getting 2 exceptions in CreateHostBuilder()
InvalidOperationException: Error while validating the service descriptor 'ServiceType: MediatR.IRequestHandler`2[Opw.PineBlog.Posts.AddPostCommand,Opw.Result`1[Opw.PineBlog.Entities.Post]] Lifetime: Transient ImplementationType: Opw.PineBlog.Posts.AddPostCommand+Handler': Unable to resolve service for type 'Opw.PineBlog.IBlogUnitOfWork' while attempting to activate 'Opw.PineBlog.Posts.AddPostCommand+Handler'.

**Comment by petervandenhout** [comment]
Hi @benmac 

The issue you are having is that you use `AddPineBlogCore` and not `AddPineBlog`. If you want to use the `AddPineBlogCore` then you explicitly need to add the `AddPineBlogEntityFrameworkCore` services as well.

```csharp
services.AddPineBlogCore(configuration);
services.AddPineBlogEntityFrameworkCore(configuration);
``` 

The default way to add the blog to your website with EF Core support is to use:

```csharp
services.AddPineBlog(configuration);
``` 

And for the `AddPineBlogEntityFrameworkCoreConfiguration` and `AddPineBlogConfiguration` the documentation was not updated everywhere, I've done that now.
