### ISSUE TITLE
.NET 6 Update

### ISSUE THREAD

**Issue by petervandenhout** [ofpinewood/pineblog#106]
Update the code for .Net 6 and stop support for .NET 5 after release of .NET 6 (around February 2022). Only support one earlier LTS version of .NET, .Net 5 is not an LTS version.

- .Net 5 End of Support: 3 months after .NET 6 release (around February 2022)
- [.NET Core and .NET 5 Support Policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)
- [.NET Release Schedule](https://github.com/dotnet/core/blob/master/roadmap.md)

**Comment by rywalters** [comment]
I'm new to GitHub, Pine Blog, and Net 6.0. Is it not currently possible to run Pine Blog on Net 6.0?

**Comment by petervandenhout** [comment]
@rywalters it is possible to use pineblog with net6, probably. It has just not been tested and the packages are not yet targeting net6. I will do this soon...
