### ISSUE TITLE
Search post functionality

### ISSUE THREAD

**Issue by tristan-hyams** [ofpinewood/pineblog#108]
I see Searching is disabled through the project and you have quite the feature list you have self-assigned... ...but none of them are enabling searching/re-enabling searching.

So I am curious as to what's the plan here for that?

Thanks for your library :)

I am trying to embed PineBlog inside a Net5.0 website right now and I think I am just really missing the ability to search posts. I can wait on comments.

**Comment by petervandenhout** [comment]
Hi @houseofcat I'll pick this up asap. At the moment I'm competing the mongodb data source issue, so that will take me a few more days. After that I'll start on the search. I expect that to be done in a week or 2 (because of holidays and such).

**Comment by petervandenhout** [comment]
Enable the search functionality in the `_Header.cshtml`.

Search in the following fields:
- `Post.Title`
- `Post.Description`
- `Post.Content`
- `Post.Categories`

Search method `freetext`, with more weight on the `Post.Categories` and `Post.Title`.

@houseofcat please let me know if you need anything more..

**Comment by tristan-hyams** [comment]
That sounds perfect @petervandenhout.

Once I start getting more familiar with it, I will be more than happy to add tweaks or help out and contribute. I intend to use it quite regularly as I rebuild my site.

https://houseofcat.io/ when it's back online!

**Comment by petervandenhout** [comment]
@houseofcat I've finished the update of PineBlog to v2.0, adding:
- `MongoDb` can now be used a data source
- Extended Markdown support
- Now targeting `net5.0` and `netcoreapp3.1`
- Removed the `_ValidationScriptsPartial` from `Opw.PineBlog.RazorPages`
- Removed dependencies on `Opw.Core` and `Opw.EntityFramework`

https://ofpinewood.com/blog/pineblog-v2

And I've started the implementation of the search functionality, I expect to finish that (at least a basic version) in the next day or two.

**Comment by tristan-hyams** [comment]
@petervandenhout bravo! o7

**Comment by petervandenhout** [comment]
@houseofcat I've completed the implementation of the search. It's available as version 2.1-beta1 on [nuget](https://www.nuget.org/packages/Opw.PineBlog).

Could you check the pull request #114 and verify on the `demo` site that it is something that works for you?

> **Url:** [pineblog.azurewebsites.net](https://pineblog.azurewebsites.net)  
> **Username:** pineblog@example.com  
> **Password:** demo  

If all is well, I'll merge it in tomorrow and create the 2.1 release.

**Comment by petervandenhout** [comment]
@houseofcat the search functionality has been added in release 2.1. If you have any (other) questions or remarks, let me know.

[Release 2.1](https://github.com/ofpinewood/pineblog/releases/tag/2.1)
[Opw.PineBlog 2.1.0](https://www.nuget.org/packages/Opw.PineBlog/2.1.0)

**Comment by tristan-hyams** [comment]
@petervandenhout thanks for the release, work has me running ragged - will play around soon and update!
