### ISSUE TITLE
RoutingOptions - Created a RouteOption config that screwed up PineBlog

### ISSUE THREAD

**Issue by tristan-hyams** [ofpinewood/pineblog#119]
Was looking to change all of my routing inside my entire AspNetCore host to lowercase convention - to look cleaner/modern.

Example configure RouteOptions.
```csharp
services.Configure<RouteOptions>(options =>
{
    options.LowercaseUrls = true;
    options.LowercaseQueryStrings = true;
    options.AppendTrailingSlash = true;
});
```

It ended up breaking the UpdatePost action of my co-hosted Admin/Blog section. I figured I was overriding one of your default settings.

Once the configuration options were enabled for example, it changed this route `/Admin/updatepost?id=uuid` which is my standard routing scheme into this route `/admin/post/updatepost?id=uuid`. Unsure of where the extra `/post/` came from.

Admin is also fully authenticated behind AspNetIdentity (I may submit this code for you as an extension for PineBlog to quickly add simple Authentication for users).

I think the bug is on my end but do you have any thoughts on how I could accomplish this?

More contextual code:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

    services
        .AddIdentity<IdentityUser, IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultTokenProviders();

    services.Configure<IdentityOptions>(options =>
    {
        options.SignIn.RequireConfirmedEmail = true;
        // Password settings.
        options.Password.RequireDigit = true;
        options.Password.RequireLowercase = true;
        options.Password.RequireNonAlphanumeric = true;
        options.Password.RequireUppercase = true;
        options.Password.RequiredLength = 8;
        options.Password.RequiredUniqueChars = 4;
        // Lockout settings.
        options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
        options.Lockout.MaxFailedAccessAttempts = 5;
        options.Lockout.AllowedForNewUsers = true;
        // User settings.
        options.User.AllowedUserNameCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._!@#$%^&*| ";
        options.User.RequireUniqueEmail = true;
        options.ClaimsIdentity.RoleClaimType = ClaimTypes.Role;
    });

    services.Configure<CookiePolicyOptions>(options =>
    {
        options.CheckConsentNeeded = context => true;
        options.MinimumSameSitePolicy = SameSiteMode.None;
    });

    services.ConfigureApplicationCookie(
        options =>
        {
            options.ExpireTimeSpan = TimeSpan.FromMinutes(10);
            options.SlidingExpiration = true;
            options.LoginPath = "/Identity/Account/Login";
            options.LogoutPath = "/Identity/Account/Logout";
        });

    services
        .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
        .AddCookie();

    //services.Configure<RouteOptions>(options =>
    //{
    //    options.LowercaseUrls = true;
    //    options.LowercaseQueryStrings = true;
    //    options.AppendTrailingSlash = true;
    //});

    services.AddMarkdown();
    services.AddPineBlog(Configuration);
    services
        .AddRazorPages()
        .AddPineBlogRazorPages()
        .AddApplicationPart(typeof(MarkdownPageProcessorMiddleware).Assembly);
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
        app.UseHsts();
    }

    app.UseHttpsRedirection();
    app.UseMarkdown();
    app.UseStaticFiles();
    app.UseCookiePolicy();

    app.UseRouting();

    app.UseAuthentication();
    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapRazorPages();
        endpoints.MapControllers();
    });
}
```

Not a huge rush to solve, I have reverted back to standard routing casing.

**Comment by petervandenhout** [comment]
@houseofcat the lowercase routes should be something that you could use. I'll see if I can make some improvements to make them possible.

**Comment by petervandenhout** [comment]
@houseofcat the lowercase routing was a bug in PineBlog, due to generating the page routes in the wrong way. I've updated that, so you should now be able to use lowercase routing. The sample application also has this enabled now.

In the `Startup.cs`.
```csharp
services.AddRouting(options => {
    options.LowercaseUrls = true;
    options.LowercaseQueryStrings = true;
    options.AppendTrailingSlash = true;
});
```

**Comment by petervandenhout** [comment]
@houseofcat for the authentication. I want to leave that out of the core packages, because I want PineBlog to be a blogging engine only. Adding authentication would add to much extra stuff that most users would want to customize anyway. 
But it might be a extra/optional package for user that just want something basic without any setup. If you like you can make a pull request with your extension :)

**Comment by petervandenhout** [comment]
@houseofcat the update is available in v2.1.2. Can you confirm it works for you as well?

**Comment by tristan-hyams** [comment]
Yep, that solved my issue. Much appreciated.

https://houseofcat.io made some fairly decent progress. Go from Html / Razorpages, to Markdown / Razorpages, to independent Markdown.MD files that are load for Razorpages, to soon streaming the markdown from cache/Github to make quick webpage edits.

**Comment by petervandenhout** [comment]
@houseofcat looks like you're making good progress :) 
Am I correct that you are trying to have the blog posts markdown stored in GitHub and then use that as a database for the posts? That sounds like an interesting idea... and a good extension for a dataprovider besides EF and MongoDb.

**Comment by tristan-hyams** [comment]
Yeah maybe like I said with an internal or external cache with expiry. Possibly even expose the guides as a separate repo my viewers could submit PRs to help keep them updated or fix documentation.

I will keep you up to date.
