### ISSUE TITLE
Add net6.0 program.cs based configuration example to documentation

### ISSUE THREAD

**Issue by petervandenhout** [ofpinewood/pineblog#149]
See: [Upgrading a .NET 5 "Startup-based" app to .NET 6](https://andrewlock.net/exploring-dotnet-6-part-12-upgrading-a-dotnet-5-startup-based-app-to-dotnet-6/)

**Comment by ScubaAddict1** [comment]
will this project work in .net 7?

**Comment by petervandenhout** [comment]
@ScubaAddict1 It will probably work fine in net7. The changes between net7 and the previous version are not so big.

**Comment by petervandenhout** [comment]
Won't do this since .NET 6 in favor of doing this for .NET 8 and/or .NET 9.
