### ISSUE TITLE
Question: Is it possible to customize the blog main page to show list of the blog articles instead of the whole article?

### ISSUE THREAD

**Issue by ScubaAddict1** [ofpinewood/pineblog#152]
Is it possible to customize the blog main page to show list of the blog articles instead of the whole article?

im thinking in the lines or cards, showing the latest articles, and perhaps adding a filter to that page with a category selecting.

**Comment by petervandenhout** [comment]
Yes that is possible. You can add a custom `Index.cshtml` page in `Areas/Blog/Pages`, and customize that all you want. Take the default as a template and start from there (`https://github.com/ofpinewood/pineblog/blob/main/src/Opw.PineBlog.RazorPages/Areas/Blog/Pages/Index.cshtml`)
